
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-event-logger-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-event-logger-role
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "get", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-event-logger-rolebinding
subjects:
- kind: ServiceAccount
  name: k8s-event-logger-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-event-logger-role
  apiGroup: rbac.authorization.k8s.io
